In [6]:
import pandas as pd
import csv
import os

from beerdata_loader import BeerDataLoader

# BeerAdvocate

**Loading the data**

In [7]:
data_loader = BeerDataLoader(data_dir="../data/BeerAdvocate", force_process=False)

ba_reviews_df, ba_ratings_df, ba_beers_df, ba_breweries_df, ba_users_df = (
    data_loader.load_all_data()
)

print("Reviews DataFrame:")
print(ba_reviews_df.head())

print("\nRatings DataFrame:")
print(ba_ratings_df.head())

print("\nBeers DataFrame:")
print(ba_beers_df.head())

print("\nBreweries DataFrame:")
print(ba_breweries_df.head())

print("\nUsers DataFrame:")
print(ba_users_df.head())

Processed file '../data/BeerAdvocate\reviews_processed.csv' already exists. Skipping processing.
Processed file '../data/BeerAdvocate\ratings_processed.csv' already exists. Skipping processing.
Reviews DataFrame:
       beer_name  beer_id                               brewery_name  \
0          Régab   142544  Societe des Brasseries du Gabon (SOBRAGA)
1  Barelegs Brew    19590       Strangford Lough Brewing Company Ltd
2  Barelegs Brew    19590       Strangford Lough Brewing Company Ltd
3  Barelegs Brew    19590       Strangford Lough Brewing Company Ltd
4  Barelegs Brew    19590       Strangford Lough Brewing Company Ltd

   brewery_id             style  abv        date        user_name  \
0       37262   Euro Pale Lager  4.5  1440064800          nmann08
1       10093  English Pale Ale  4.5  1235127600      StJamesGate
2       10093  English Pale Ale  4.5  1142247600          mdagnew
3       10093  English Pale Ale  4.5  1101898800  helloloser12345
4       10093  English Pale Ale  4.5  1093860000       cypressbob

                 user_id  appearance  aroma  palate  taste  overall  rating  \
0         nmann08.184925        3.25   2.75    3.25   2.75      3.0    2.88
1     stjamesgate.163714        3.00   3.50    3.50   4.00      3.5    3.67
2          mdagnew.19527        4.00   3.50    3.50   4.00      3.5    3.73
3  helloloser12345.10867        4.00   3.50    4.00   4.00      4.5    3.98
4        cypressbob.3708        4.00   4.00    4.00   4.00      4.0    4.00

                                                text
0  From a bottle, pours a piss yellow color with ...
1  Pours pale copper with a thin head that quickl...
2  500ml Bottle bought from The Vintage, Antrim.....
3  Serving: 500ml brown bottlePour: Good head wit...
4  500ml bottlePours with a light, slightly hazy ...

Ratings DataFrame:
       beer_name  beer_id                               brewery_name  \
0          Régab   142544  Societe des Brasseries du Gabon (SOBRAGA)
1  Barelegs Brew    19590       Strangford Lough Brewing Company Ltd
2  Barelegs Brew    19590       Strangford Lough Brewing Company Ltd
3  Barelegs Brew    19590       Strangford Lough Brewing Company Ltd
4  Barelegs Brew    19590       Strangford Lough Brewing Company Ltd

   brewery_id             style  abv        date        user_name  \
0       37262   Euro Pale Lager  4.5  1440064800          nmann08
1       10093  English Pale Ale  4.5  1235127600      StJamesGate
2       10093  English Pale Ale  4.5  1142247600          mdagnew
3       10093  English Pale Ale  4.5  1101898800  helloloser12345
4       10093  English Pale Ale  4.5  1093860000       cypressbob

                 user_id  appearance  aroma  palate  taste  overall  rating  \
0         nmann08.184925        3.25   2.75    3.25   2.75      3.0    2.88
1     stjamesgate.163714        3.00   3.50    3.50   4.00      3.5    3.67
2          mdagnew.19527        4.00   3.50    3.50   4.00      3.5    3.73
3  helloloser12345.10867        4.00   3.50    4.00   4.00      4.5    3.98
4        cypressbob.3708        4.00   4.00    4.00   4.00      4.0    4.00

                                                text  review
0  From a bottle, pours a piss yellow color with ...    True
1  Pours pale copper with a thin head that quickl...    True
2  500ml Bottle bought from The Vintage, Antrim.....    True
3  Serving: 500ml brown bottlePour: Good head wit...    True
4  500ml bottlePours with a light, slightly hazy ...    True

Beers DataFrame:
   beer_id           beer_name  brewery_id            brewery_name  \
0   166064    Nashe Moskovskoe       39912  Abdysh-Ata (Абдыш Ата)
1   166065     Nashe Pivovskoe       39912  Abdysh-Ata (Абдыш Ата)
2   166066  Nashe Shakhterskoe       39912  Abdysh-Ata (Абдыш Ата)
3   166067  Nashe Zhigulevskoe       39912  Abdysh-Ata (Абдыш Ата)
4   166063              Zhivoe       39912  Abdysh-Ata (Абдыш Ата)

             style  nbr_ratings  nbr_reviews  avg  ba_score  bros_score  abv  \
0  Euro Pale Lager            0            0  NaN       NaN         NaN  4.7
1  Euro Pale Lager            0            0  NaN       NaN         NaN  3.8
2  Euro Pale Lager            0            0  NaN       NaN         NaN  4.8
3  Euro Pale Lager            0            0  NaN       NaN         NaN  4.0
4  Euro Pale Lager            0            0  NaN       NaN         NaN  4.5

   avg_computed  zscore  nbr_matched_valid_ratings  avg_matched_valid_ratings
0           NaN     NaN                          0                        NaN
1           NaN     NaN                          0                        NaN
2           NaN     NaN                          0                        NaN
3           NaN     NaN                          0                        NaN
4           NaN     NaN                          0                        NaN

Breweries DataFrame:
      id    location                    name  nbr_beers
0  39912  Kyrgyzstan  Abdysh-Ata (Абдыш Ата)          5
1  39913  Kyrgyzstan             Arpa (АРПА)          1
2  39914  Kyrgyzstan               Bear Beer          4
3  39915  Kyrgyzstan             Blonder Pub          4
4  39916  Kyrgyzstan            Kellers Bier          2

Users DataFrame:
   nbr_ratings  nbr_reviews                user_id        user_name  \
0         7820          465         nmann08.184925          nmann08
1         2521         2504     stjamesgate.163714      StJamesGate
2         1797         1143          mdagnew.19527          mdagnew
3           31           31  helloloser12345.10867  helloloser12345
4          604          604        cypressbob.3708       cypressbob

         joined                   location
0  1.199704e+09  United States, Washington
1  1.191838e+09    United States, New York
2  1.116410e+09           Northern Ireland
3  1.101380e+09           Northern Ireland
4  1.069326e+09           Northern Ireland

In [9]:
# Function to describe and explore each dataset
def explore_data(df, df_name):
    print(f"\n--- {df_name} ---\n")
    # Show the first few rows
    print("First few rows:")
    print(df.head())
    
    # Show basic information (column types, non-null counts, memory usage)
    print("\nDataFrame info:")
    df.info()
    
    # Describe numerical columns
    print("\nNumerical Data Summary:")
    print(df.describe())

    # Separate handling for object and category columns
    non_numerical_cols = df.select_dtypes(include=['object', 'category']).columns
    if len(non_numerical_cols) > 0:
        print("\nNon-Numerical Data Summary (objects and categories):")
        print(df[non_numerical_cols].describe())

    # Check for missing values
    print("\nMissing Values:")
    print(df.isnull().sum())
    
    # Check the number of unique values for each column
    print("\nUnique values per column:")
    print(df.nunique())

# Explore each dataset
explore_data(ba_reviews_df, "Reviews DataFrame")
explore_data(ba_ratings_df, "Ratings DataFrame")
explore_data(ba_beers_df, "Beers DataFrame")
explore_data(ba_breweries_df, "Breweries DataFrame")
explore_data(ba_users_df, "Users DataFrame")

--- Reviews DataFrame ---

First few rows:
       beer_name  beer_id                               brewery_name  \
0          Régab   142544  Societe des Brasseries du Gabon (SOBRAGA)
1  Barelegs Brew    19590       Strangford Lough Brewing Company Ltd
2  Barelegs Brew    19590       Strangford Lough Brewing Company Ltd
3  Barelegs Brew    19590       Strangford Lough Brewing Company Ltd
4  Barelegs Brew    19590       Strangford Lough Brewing Company Ltd

   brewery_id             style  abv        date        user_name  \
0       37262   Euro Pale Lager  4.5  1440064800          nmann08
1       10093  English Pale Ale  4.5  1235127600      StJamesGate
2       10093  English Pale Ale  4.5  1142247600          mdagnew
3       10093  English Pale Ale  4.5  1101898800  helloloser12345
4       10093  English Pale Ale  4.5  1093860000       cypressbob

                 user_id  appearance  aroma  palate  taste  overall  rating  \
0         nmann08.184925        3.25   2.75    3.25   2.75      3.0    2.88
1     stjamesgate.163714        3.00   3.50    3.50   4.00      3.5    3.67
2          mdagnew.19527        4.00   3.50    3.50   4.00      3.5    3.73
3  helloloser12345.10867        4.00   3.50    4.00   4.00      4.5    3.98
4        cypressbob.3708        4.00   4.00    4.00   4.00      4.0    4.00

                                                text
0  From a bottle, pours a piss yellow color with ...
1  Pours pale copper with a thin head that quickl...
2  500ml Bottle bought from The Vintage, Antrim.....
3  Serving: 500ml brown bottlePour: Good head wit...
4  500ml bottlePours with a light, slightly hazy ...

DataFrame info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2589586 entries, 0 to 2589585
Data columns (total 16 columns):
 #   Column        Dtype
---  ------        -----
 0   beer_name     object
 1   beer_id       int64
 2   brewery_name  object
 3   brewery_id    int64
 4   style         object
 5   abv           float64
 6   date          int64
 7   user_name     object
 8   user_id       object
 9   appearance    float64
 10  aroma         float64
 11  palate        float64
 12  taste         float64
 13  overall       float64
 14  rating        float64
 15  text          object
dtypes: float64(7), int64(3), object(6)
memory usage: 316.1+ MB

Numerical Data Summary:
            beer_id    brewery_id           abv          date    appearance  \
count  2.589586e+06  2.589586e+06  2.523603e+06  2.589586e+06  2.557577e+06
mean   5.039168e+04  6.604292e+03  7.196049e+00  1.304753e+09  3.884245e+00
std    5.929567e+04  1.066712e+04  2.386648e+00  1.126194e+08  5.868417e-01
min    3.000000e+00  1.000000e+00  1.000000e-02  8.407080e+08  1.000000e+00
25%    3.811000e+03  1.480000e+02  5.400000e+00  1.229857e+09  3.500000e+00
50%    3.442000e+04  6.820000e+02  6.700000e+00  1.306577e+09  4.000000e+00
75%    6.949300e+04  1.060700e+04  8.500000e+00  1.394449e+09  4.250000e+00
max    2.932850e+05  4.981500e+04  6.750000e+01  1.501582e+09  5.000000e+00

              aroma        palate         taste       overall        rating
count  2.557577e+06  2.557577e+06  2.557577e+06  2.557577e+06  2.589586e+06
mean   3.794767e+00  3.798682e+00  3.836279e+00  3.846197e+00  3.828833e+00
std    6.611576e-01  6.507799e-01  6.936974e-01  6.719210e-01  6.014400e-01
min    1.000000e+00  1.000000e+00  1.000000e+00  1.000000e+00  1.000000e+00
25%    3.500000e+00  3.500000e+00  3.500000e+00  3.500000e+00  3.530000e+00
50%    4.000000e+00  4.000000e+00  4.000000e+00  4.000000e+00  3.930000e+00
75%    4.250000e+00  4.000000e+00  4.250000e+00  4.250000e+00  4.220000e+00
max    5.000000e+00  5.000000e+00  5.000000e+00  5.000000e+00  5.000000e+00

Non-Numerical Data Summary (objects and categories):
            beer_name                        brewery_name         style  \
count         2589586                             2589586       2589586
unique         145206                               11817           104
top     90 Minute IPA  Boston Beer Company (Samuel Adams)  American IPA
freq             3899                               52883        248781

            user_name               user_id  \
count         2589583               2589586
unique          62251                 62252
top     StonedTrippin  stonedtrippin.601042
freq             8970                  8970

                                                     text
count                                             2589584
unique                                            2587998
top     Pours a light yellow color, nice carbonation, ...
freq                                                   37

Missing Values:
beer_name           0
beer_id             0
brewery_name        0
brewery_id          0
style               0
abv             65983
date                0
user_name           3
user_id             0
appearance      32009
aroma           32009
palate          32009
taste           32009
overall         32009
rating              0
text                2
dtype: int64

Unique values per column:
beer_name        145206
beer_id          166649
brewery_name      11817
brewery_id        11968
style               104
abv                 751
date               6117
user_name         62251
user_id           62252
appearance           17
aroma                17
palate               17
taste                17
overall              17
rating              401
text            2587998
dtype: int64

--- Ratings DataFrame ---

First few rows:
       beer_name  beer_id                               brewery_name  \
0          Régab   142544  Societe des Brasseries du Gabon (SOBRAGA)
1  Barelegs Brew    19590       Strangford Lough Brewing Company Ltd
2  Barelegs Brew    19590       Strangford Lough Brewing Company Ltd
3  Barelegs Brew    19590       Strangford Lough Brewing Company Ltd
4  Barelegs Brew    19590       Strangford Lough Brewing Company Ltd

   brewery_id             style  abv        date        user_name  \
0       37262   Euro Pale Lager  4.5  1440064800          nmann08
1       10093  English Pale Ale  4.5  1235127600      StJamesGate
2       10093  English Pale Ale  4.5  1142247600          mdagnew
3       10093  English Pale Ale  4.5  1101898800  helloloser12345
4       10093  English Pale Ale  4.5  1093860000       cypressbob

                 user_id  appearance  aroma  palate  taste  overall  rating  \
0         nmann08.184925        3.25   2.75    3.25   2.75      3.0    2.88
1     stjamesgate.163714        3.00   3.50    3.50   4.00      3.5    3.67
2          mdagnew.19527        4.00   3.50    3.50   4.00      3.5    3.73
3  helloloser12345.10867        4.00   3.50    4.00   4.00      4.5    3.98
4        cypressbob.3708        4.00   4.00    4.00   4.00      4.0    4.00

                                                text  review
0  From a bottle, pours a piss yellow color with ...    True
1  Pours pale copper with a thin head that quickl...    True
2  500ml Bottle bought from The Vintage, Antrim.....    True
3  Serving: 500ml brown bottlePour: Good head wit...    True
4  500ml bottlePours with a light, slightly hazy ...    True

DataFrame info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8393032 entries, 0 to 8393031
Data columns (total 17 columns):
 #   Column        Dtype
---  ------        -----
 0   beer_name     category
 1   beer_id       int32
 2   brewery_name  category
 3   brewery_id    int32
 4   style         category
 5   abv           float32
 6   date          int64
 7   user_name     category
 8   user_id       category
 9   appearance    float32
 10  aroma         float32
 11  palate        float32
 12  taste         float32
 13  overall       float32
 14  rating        float32
 15  text          string
 16  review        bool
dtypes: bool(1), category(5), float32(7), int32(2), int64(1), string(1)
memory usage: 565.0 MB

Numerical Data Summary:
            beer_id    brewery_id           abv          date    appearance  \
count  8.393032e+06  8.393032e+06  8.221727e+06  8.393032e+06  4.769675e+06
mean   6.675445e+04  9.129888e+03  7.330264e+00  1.375265e+09  3.937207e+00
std    6.481824e+04  1.237611e+04  2.459114e+00  8.678273e+07  5.584127e-01
min    3.000000e+00  1.000000e+00  1.000000e-02  8.407080e+08  1.000000e+00
25%    9.074000e+03  1.920000e+02  5.500000e+00  1.339322e+09  3.750000e+00
50%    5.226600e+04  1.142000e+03  6.900000e+00  1.395227e+09  4.000000e+00
75%    9.654800e+04  1.800600e+04  8.800000e+00  1.431684e+09  4.250000e+00
max    2.932960e+05  4.981500e+04  6.750000e+01  1.501582e+09  5.000000e+00

              aroma        palate         taste       overall        rating
count  4.769675e+06  4.769675e+06  4.769675e+06  4.769675e+06  8.393032e+06
mean   3.869603e+00  3.865859e+00  3.903288e+00  3.900529e+00  3.882132e+00
std    6.204451e-01  6.083913e-01  6.433164e-01  6.161058e-01  6.205087e-01
min    1.000000e+00  1.000000e+00  1.000000e+00  1.000000e+00  1.000000e+00
25%    3.500000e+00  3.500000e+00  3.500000e+00  3.500000e+00  3.540000e+00
50%    4.000000e+00  4.000000e+00  4.000000e+00  4.000000e+00  4.000000e+00
75%    4.250000e+00  4.250000e+00  4.250000e+00  4.250000e+00  4.250000e+00
max    5.000000e+00  5.000000e+00  5.000000e+00  5.000000e+00  5.000000e+00

Non-Numerical Data Summary (objects and categories):
                       beer_name   brewery_name         style user_name  \
count                    8393032        8393032       8393032   8393001
unique                    211056          13440           104    153703
top     Founders Breakfast Stout  Stone Brewing  American IPA     Sammy
freq                       16509         165752        997814     12046

           user_id
count      8393032
unique      153704
top     sammy.3853
freq         12046

Missing Values:
beer_name             0
beer_id               0
brewery_name          0
brewery_id            0
style                 0
abv              171305
date                  0
user_name            31
user_id               0
appearance      3623357
aroma           3623357
palate          3623357
taste           3623357
overall         3623357
rating                0
text            5677323
review                0
dtype: int64

Unique values per column:
beer_name        211056
beer_id          247982
brewery_name      13440
brewery_id        13624
style               104
abv                 843
date               6135
user_name        153703
user_id          153704
appearance           17
aroma                17
palate               17
taste                17
overall              17
rating              401
text            2708659
review                2
dtype: int64

--- Beers DataFrame ---

First few rows:
   beer_id           beer_name  brewery_id            brewery_name  \
0   166064    Nashe Moskovskoe       39912  Abdysh-Ata (Абдыш Ата)
1   166065     Nashe Pivovskoe       39912  Abdysh-Ata (Абдыш Ата)
2   166066  Nashe Shakhterskoe       39912  Abdysh-Ata (Абдыш Ата)
3   166067  Nashe Zhigulevskoe       39912  Abdysh-Ata (Абдыш Ата)
4   166063              Zhivoe       39912  Abdysh-Ata (Абдыш Ата)

             style  nbr_ratings  nbr_reviews  avg  ba_score  bros_score  abv  \
0  Euro Pale Lager            0            0  NaN       NaN         NaN  4.7
1  Euro Pale Lager            0            0  NaN       NaN         NaN  3.8
2  Euro Pale Lager            0            0  NaN       NaN         NaN  4.8
3  Euro Pale Lager            0            0  NaN       NaN         NaN  4.0
4  Euro Pale Lager            0            0  NaN       NaN         NaN  4.5

   avg_computed  zscore  nbr_matched_valid_ratings  avg_matched_valid_ratings
0           NaN     NaN                          0                        NaN
1           NaN     NaN                          0                        NaN
2           NaN     NaN                          0                        NaN
3           NaN     NaN                          0                        NaN
4           NaN     NaN                          0                        NaN

DataFrame info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 280823 entries, 0 to 280822
Data columns (total 15 columns):
 #   Column                     Non-Null Count   Dtype
---  ------                     --------------   -----
 0   beer_id                    280823 non-null  int64
 1   beer_name                  280823 non-null  object
 2   brewery_id                 280823 non-null  int64
 3   brewery_name               280823 non-null  object
 4   style                      280823 non-null  object
 5   nbr_ratings                280823 non-null  int64
 6   nbr_reviews                280823 non-null  int64
 7   avg                        247994 non-null  float64
 8   ba_score                   61200 non-null   float64
 9   bros_score                 5702 non-null    float64
 10  abv                        244799 non-null  float64
 11  avg_computed               247982 non-null  float64
 12  zscore                     40285 non-null   float64
 13  nbr_matched_valid_ratings  280823 non-null  int64
 14  avg_matched_valid_ratings  28272 non-null   float64
dtypes: float64(7), int64(5), object(3)
memory usage: 32.1+ MB

Numerical Data Summary:
             beer_id     brewery_id    nbr_ratings    nbr_reviews  \
count  280823.000000  280823.000000  280823.000000  280823.000000
mean   148556.817141   21335.895860      29.887267       9.221417
std     84307.593397   15385.715656     231.010063      68.866445
min         3.000000       1.000000       0.000000       0.000000
25%     76513.500000    3835.000000       1.000000       0.000000
50%    148867.000000   24075.000000       2.000000       1.000000
75%    221817.500000   33960.000000       8.000000       2.000000
max    293296.000000   49817.000000   16509.000000    3899.000000

                 avg      ba_score   bros_score            abv   avg_computed  \
count  247994.000000  61200.000000  5702.000000  244799.000000  247982.000000
mean        3.721034     84.633284    84.806559       6.491370       3.717594
std         0.476003      4.052723    10.507735       2.054071       0.464248
min         0.000000     46.000000    31.000000       0.010000       1.000000
25%         3.500000     83.000000    81.000000       5.000000       3.500000
50%         3.780000     85.000000    87.000000       6.000000       3.770000
75%         4.010000     86.000000    91.000000       7.500000       4.000000
max         5.000000    100.000000   100.000000      67.500000       5.000000

             zscore  nbr_matched_valid_ratings  avg_matched_valid_ratings
count  40285.000000              280823.000000               28272.000000
mean      -0.408295                   1.029207                   3.747771
std        0.806491                  17.295308                   0.484775
min       -6.655704                   0.000000                   1.000000
25%       -0.785424                   0.000000                   3.520000
50%       -0.321596                   0.000000                   3.808333
75%        0.086733                   0.000000                   4.045000
max        2.211576                2968.000000                   5.000000

Non-Numerical Data Summary (objects and categories):
          beer_name                      brewery_name         style
count        280823                            280823        280823
unique       236209                             14098           104
top     Oktoberfest  Rock Bottom Restaurant & Brewery  American IPA
freq            577                              1219         30433

Missing Values:
beer_id                           0
beer_name                         0
brewery_id                        0
brewery_name                      0
style                             0
nbr_ratings                       0
nbr_reviews                       0
avg                           32829
ba_score                     219623
bros_score                   275121
abv                           36024
avg_computed                  32841
zscore                       240538
nbr_matched_valid_ratings         0
avg_matched_valid_ratings    252551
dtype: int64

Unique values per column:
beer_id                      280823
beer_name                    236209
brewery_id                    14325
brewery_name                  14098
style                           104
nbr_ratings                    2058
nbr_reviews                    1058
avg                             401
ba_score                         55
bros_score                       70
abv                             868
avg_computed                  47941
zscore                        27844
nbr_matched_valid_ratings       359
avg_matched_valid_ratings      6628
dtype: int64

--- Breweries DataFrame ---

First few rows:
      id    location                    name  nbr_beers
0  39912  Kyrgyzstan  Abdysh-Ata (Абдыш Ата)          5
1  39913  Kyrgyzstan             Arpa (АРПА)          1
2  39914  Kyrgyzstan               Bear Beer          4
3  39915  Kyrgyzstan             Blonder Pub          4
4  39916  Kyrgyzstan            Kellers Bier          2

DataFrame info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16758 entries, 0 to 16757
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   id         16758 non-null  int64
 1   location   16758 non-null  object
 2   name       16758 non-null  object
 3   nbr_beers  16758 non-null  int64
dtypes: int64(2), object(2)
memory usage: 523.8+ KB

Numerical Data Summary:
                 id     nbr_beers
count  16758.000000  16758.000000
mean   25954.841270     21.056331
std    16219.989105     69.417841
min        1.000000      0.000000
25%     9741.250000      2.000000
50%    29178.000000      6.000000
75%    40788.250000     18.000000
max    49817.000000   1196.000000

Non-Numerical Data Summary (objects and categories):
       location                         name
count     16758                        16758
unique      297                        16237
top     Germany  Granite City Food & Brewery
freq       1431                           34

Missing Values:
id           0
location     0
name         0
nbr_beers    0
dtype: int64

Unique values per column:
id           16758
location       297
name         16237
nbr_beers      273
dtype: int64

--- Users DataFrame ---

First few rows:
   nbr_ratings  nbr_reviews                user_id        user_name  \
0         7820          465         nmann08.184925          nmann08
1         2521         2504     stjamesgate.163714      StJamesGate
2         1797         1143          mdagnew.19527          mdagnew
3           31           31  helloloser12345.10867  helloloser12345
4          604          604        cypressbob.3708       cypressbob

         joined                   location
0  1.199704e+09  United States, Washington
1  1.191838e+09    United States, New York
2  1.116410e+09           Northern Ireland
3  1.101380e+09           Northern Ireland
4  1.069326e+09           Northern Ireland

DataFrame info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 153704 entries, 0 to 153703
Data columns (total 6 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   nbr_ratings  153704 non-null  int64
 1   nbr_reviews  153704 non-null  int64
 2   user_id      153704 non-null  object
 3   user_name    153703 non-null  object
 4   joined       151052 non-null  float64
 5   location     122425 non-null  object
dtypes: float64(1), int64(2), object(3)
memory usage: 7.0+ MB

Numerical Data Summary:
         nbr_ratings    nbr_reviews        joined
count  153704.000000  153704.000000  1.510520e+05
mean       54.605163      16.847876  1.357238e+09
std       252.388790     139.846706  9.195131e+07
min         1.000000       0.000000  8.407944e+08
25%         1.000000       0.000000  1.303121e+09
50%         3.000000       0.000000  1.391944e+09
75%        16.000000       2.000000  1.417691e+09

In [3]:
data_loader = BeerDataLoader(data_dir="../data/RateBeer", force_process=False)

rb_reviews_df, rb_ratings_df, rb_beers_df, rb_breweries_df, rb_users_df = (
    data_loader.load_all_data()
)

print("Reviews DataFrame:")
print(rb_reviews_df.head())

print("\nRatings DataFrame:")
print(rb_ratings_df.head())

print("\nBeers DataFrame:")
print(rb_beers_df.head())

print("\nBreweries DataFrame:")
print(rb_breweries_df.head())

print("\nUsers DataFrame:")
print(rb_users_df.head())

Processed file '../data/RateBeer\reviews_processed.csv' already exists. Skipping processing.
Processed file '../data/RateBeer\ratings_processed.csv' already exists. Skipping processing.
Reviews DataFrame:
             beer_name  beer_id brewery_name  brewery_id       style  abv  \
0    33 Export (Gabon)   410549      Sobraga        3198  Pale Lager  5.0
1  Castel Beer (Gabon)   105273      Sobraga        3198  Pale Lager  5.2
2  Castel Beer (Gabon)   105273      Sobraga        3198  Pale Lager  5.2
3  Castel Beer (Gabon)   105273      Sobraga        3198  Pale Lager  5.2
4  Castel Beer (Gabon)   105273      Sobraga        3198  Pale Lager  5.2

         date     user_name  user_id  appearance  aroma  palate  taste  \
0  1461664800       Manslow   175852           2      4       2      4
1  1487329200  MAGICuenca91   442761           2      3       2      4
2  1466762400        Sibarh   288889           3      3       2      3
3  1451646000       fombe89   250510           4      3       1      2
4  1445594400    kevnic2008   122778           2      4       2      4

   overall  rating                                               text
0        8     2.0  Puszka 0,33l dzięki Christoph . Kolor jasnozło...
1        8     1.9  Cerveza pale lager gabonesa. MÃ¡s floja que la...
2        5     1.6  Kolor- złoty, klarowny. Piana - drobna, średni...
3        5     1.5  Botella, de GabÃ³n regalo familiar.31/01/2015C...
4        7     1.9  Many thanks for this beer to Erzengel. Pours l...

Ratings DataFrame:
             beer_name  beer_id brewery_name  brewery_id       style  abv  \
0    33 Export (Gabon)   410549      Sobraga        3198  Pale Lager  5.0
1  Castel Beer (Gabon)   105273      Sobraga        3198  Pale Lager  5.2
2  Castel Beer (Gabon)   105273      Sobraga        3198  Pale Lager  5.2
3  Castel Beer (Gabon)   105273      Sobraga        3198  Pale Lager  5.2
4  Castel Beer (Gabon)   105273      Sobraga        3198  Pale Lager  5.2

         date     user_name user_id  appearance  aroma  palate  taste  \
0  1461664800       Manslow  175852         2.0    4.0     2.0    4.0
1  1487329200  MAGICuenca91  442761         2.0    3.0     2.0    4.0
2  1466762400        Sibarh  288889         3.0    3.0     2.0    3.0
3  1451646000       fombe89  250510         4.0    3.0     1.0    2.0
4  1445594400    kevnic2008  122778         2.0    4.0     2.0    4.0

   overall  rating                                               text  review
0      8.0     2.0  Puszka 0,33l dzięki Christoph . Kolor jasnozło...   False
1      8.0     1.9  Cerveza pale lager gabonesa. MÃ¡s floja que la...   False
2      5.0     1.6  Kolor- złoty, klarowny. Piana - drobna, średni...   False
3      5.0     1.5  Botella, de GabÃ³n regalo familiar.31/01/2015C...   False
4      7.0     1.9  Many thanks for this beer to Erzengel. Pours l...   False

Beers DataFrame:
   beer_id               beer_name  brewery_id      brewery_name  \
0   410549       33 Export (Gabon)        3198           Sobraga
1   105273     Castel Beer (Gabon)        3198           Sobraga
2    19445                   Régab        3198           Sobraga
3   155699  Ards Bally Black Stout       13538  Ards Brewing Co.
4   239097        Ards Belfast 366       13538  Ards Brewing Co.

                  style  nbr_ratings  overall_score  style_score   avg  abv  \
0            Pale Lager            1            NaN          NaN  2.72  5.0
1            Pale Lager           10            5.0         58.0  2.18  5.2
2            Pale Lager           27            1.0         22.0  1.83  4.5
3                 Stout            6            NaN          NaN  3.18  4.6
4  Golden Ale/Blond Ale            1            NaN          NaN  2.79  4.2

   avg_computed    zscore  nbr_matched_valid_ratings  \
0      2.000000       NaN                          0
1      1.910000       NaN                          0
2      1.811111       NaN                          0
3      3.866667  0.823699                          6
4      3.000000       NaN                          0

   avg_matched_valid_ratings
0                        NaN
1                        NaN
2                        NaN
3                   3.866667
4                        NaN

Breweries DataFrame:
      id          location                       name  nbr_beers
0   3198             Gabon                    Sobraga          3
1  13538  Northern Ireland           Ards Brewing Co.         13
2  22304  Northern Ireland  Barrahooley Craft Brewery          4
3  22818  Northern Ireland                   Boundary         66
4  24297  Northern Ireland            Brewbot Belfast          3

Users DataFrame:
   nbr_ratings  user_id     user_name        joined location
0         1890   175852       Manslow  1.337508e+09   Poland
1           89   442761  MAGICuenca91  1.484046e+09    Spain
2          169   288889        Sibarh  1.384600e+09   Poland
3         3371   250510       fombe89  1.363950e+09    Spain
4        13043   122778    kevnic2008  1.296644e+09  Germany